"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { Toaster } from 'react-hot-toast';
import ThemeToggle from '@/components/ThemeToggle';
import { ThemeProvider } from '@/context/ThemeContext';
import { useEffect } from 'react';
import { useRouter } from 'next/navigation';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const router = useRouter();

  useEffect(() => {
    const user = localStorage.getItem('user');
    if (!user && !window.location.pathname.startsWith('/login')) {
      router.replace('/login');
    }
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>

    <nav
     className="p-4 border-b flex gap-4"
     style={{ backgroundColor: 'var(--navbar)' }}
    >
          <Link href="/" className="font-semibold">Dashboard</Link>
          <Link href="/bookmarks">Bookmarks</Link>
          <Link href="/analytics">Analytics</Link>
          <Toaster position="top-right" />
        </nav>
          {children}
          
        </ThemeProvider>

      </body>
    </html>
  );
}
